### ISSUE TITLE
duplicate C function generated

### ISSUE THREAD

**Issue by matthiasr** [samrushing/irken-compiler#7]
Hi,

clang cannot compile the C generated from the following program, citing `redefinition of 'FUN_primes_106_0'`:

``` scheme
(include "lib/core.scm")
(include "lib/pair.scm")

(define isprime?
  n () -> #t
  n (p . ps) -> (if (zero? (remainder n p))
                #f
                (isprime? n ps)))

(define (primes limit n ps)
  (cond
    ((>= n limit) ps)
    ((isprime? n ps) (primes limit (+ n 1) (cons n ps)))
    (else (primes limit (+ n 1) ps))))

(primes 100 2 (list:nil))
```

Eyeballing the C code the two definitions seem to have different paths of the cond?

Bisecting it down, this was introduced in commit 02d25628823ae84f49ad4b1fe864e6b9ff0f2da7.
